base:
  outputs:

    dev:
      type: postgres
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'postgres') }}"
      schema: public

  target: dev
